
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Deliberately process.env.DATABASE_URL, not prisma/config's own env() helper: env() throws if
// the variable is missing, and this config file is loaded for EVERY prisma command, including
// `generate` — which only reads the schema file and needs no working connection string at all.
// A build step that runs `prisma generate` before DATABASE_URL is available (postinstall, on a
// fresh clone, or on a host where env vars land after npm install) would otherwise fail for no
// real reason. Anything that actually needs a live connection (migrate, db push, the app itself
// at runtime) still fails with its own clear error the moment it tries to use an empty string.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
