import type { Metadata } from "next";
import { LegalPageLayout } from "@/components/legal/legal-page-layout";

export const metadata: Metadata = {
  title: "Terms and Conditions - PlacementPilot",
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms and Conditions" lastUpdated="2026-09-15">
      <p>
        These terms cover your use of PlacementPilot, a self-hosted tool for tracking placement and graduate job
        applications. By running or using the application, you agree to the points below.
      </p>

      <section>
        <h2 className="text-base font-semibold">What this is</h2>
        <p className="mt-2 text-muted-foreground">
          PlacementPilot is provided as a local application that runs on your own device, without warranty of any
          kind, express or implied. It is offered as-is and as-available. You are responsible for keeping your own
          backups of the data it stores.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold">AI features</h2>
        <p className="mt-2 text-muted-foreground">
          Optional AI features (job analysis, CV matching, document tailoring) call the Anthropic API using an API
          key you supply and are billed for directly by Anthropic. Use of these features is subject to
          Anthropic&apos;s own terms of service. Content generated by these features is a draft only: you are
          responsible for reviewing it for accuracy before relying on it, including before sending a CV or cover
          letter to an employer.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold">Plans and payment</h2>
        <p className="mt-2 text-muted-foreground">
          The Free and Pro plans described on the landing page and in the app&apos;s Account settings are not
          currently connected to a real payment processor. No charge is made for selecting &quot;Pro&quot; today. If and
          when real billing is introduced, these terms will be updated to reflect it before any payment is
          collected.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold">Acceptable use</h2>
        <p className="mt-2 text-muted-foreground">
          Don&apos;t use this application for an unlawful purpose, and don&apos;t use the AI features to generate content
          intended to mislead an employer (for example, fabricating qualifications or experience you don&apos;t have).
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold">Limitation of liability</h2>
        <p className="mt-2 text-muted-foreground">
          To the fullest extent permitted by law, PlacementPilot is not liable for any loss of data, missed
          deadlines, or outcomes from job applications tracked or generated using this application. You remain
          responsible for your own applications and their outcomes.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold">Changes to these terms</h2>
        <p className="mt-2 text-muted-foreground">
          These terms may change as the application changes. Continued use after an update means you accept the
          revised terms.
        </p>
      </section>
    </LegalPageLayout>
  );
}
